import { create } from 'zustand'
import type { PlanChunk, PlanResult } from '@intentos/shared-types'

export interface GenProgress {
  stage: 'codegen' | 'compile' | 'bundle' | 'complete' | 'error'
  progress: number
  message: string
}

export interface GenError {
  message: string
  code: string
}

interface GenerationStore {
  // Phase: 1 = Skill selection + intent, 2 = planning interaction, 3 = generation progress
  phase: 1 | 2 | 3
  sessionId: string | null

  // Phase 2: planning
  planChunks: PlanChunk[]
  planResult: PlanResult | null
  isPlanning: boolean

  // Phase 3: generation progress
  genProgress: GenProgress | null
  isGenerating: boolean
  genError: GenError | null
  genComplete: boolean

  // actions
  setPhase: (phase: 1 | 2 | 3) => void
  setSessionId: (id: string) => void
  appendPlanChunk: (chunk: PlanChunk) => void
  setPlanResult: (result: PlanResult) => void
  setIsPlanning: (v: boolean) => void
  setGenProgress: (p: GenProgress) => void
  setIsGenerating: (v: boolean) => void
  setGenError: (e: GenError | null) => void
  setGenComplete: (v: boolean) => void

  startPlan: (skillIds: string[], intent: string) => Promise<void>
  refinePlan: (feedback: string) => Promise<void>
  confirmGenerate: (appName: string) => Promise<void>
  reset: () => void
}

const initialState = {
  phase: 1 as const,
  sessionId: null,
  planChunks: [],
  planResult: null,
  isPlanning: false,
  genProgress: null,
  isGenerating: false,
  genError: null,
  genComplete: false,
}

export const useGenerationStore = create<GenerationStore>((set, get) => ({
  ...initialState,

  setPhase: (phase) => set({ phase }),
  setSessionId: (id) => set({ sessionId: id }),
  appendPlanChunk: (chunk) =>
    set((s) => ({ planChunks: [...s.planChunks, chunk] })),
  setPlanResult: (result) => set({ planResult: result }),
  setIsPlanning: (v) => set({ isPlanning: v }),
  setGenProgress: (p) => set({ genProgress: p }),
  setIsGenerating: (v) => set({ isGenerating: v }),
  setGenError: (e) => set({ genError: e }),
  setGenComplete: (v) => set({ genComplete: v }),

  startPlan: async (skillIds, intent) => {
    set({ sessionId: null, planChunks: [], planResult: null, isPlanning: true, genError: null })
    try {
      // sessionId is generated by the main process and returned synchronously.
      // We must NOT generate our own UUID — the IPC push channels use the main-process ID.
      const result = await window.intentOS.generation.startPlan({ skillIds, intent })
      const sessionId: string = (result as any)?.data?.sessionId ?? (result as any)?.sessionId
      // Store sessionId so GenerationWindow useEffect re-runs and subscribes to chunk events.
      // Streaming starts asynchronously on the main side after this invoke returns,
      // so the subscription is guaranteed to be in place before the first chunk arrives.
      set({ sessionId, phase: 2 })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isPlanning: false,
        genError: { message, code: 'START_PLAN_FAILED' },
      })
      throw err
    }
  },

  refinePlan: async (feedback) => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ isPlanning: true, planChunks: [] })
    try {
      await window.intentOS.generation.refinePlan({ sessionId, feedback })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isPlanning: false,
        genError: { message, code: 'REFINE_PLAN_FAILED' },
      })
      throw err
    }
  },

  confirmGenerate: async (appName) => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ isGenerating: true, genError: null, phase: 3 })
    try {
      await window.intentOS.generation.confirmAndGenerate({ sessionId, appName })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isGenerating: false,
        genError: { message, code: 'CONFIRM_GENERATE_FAILED' },
      })
      throw err
    }
  },

  reset: () => set({ ...initialState }),
}))
