import { create } from 'zustand'
import type { PlanChunk, PlanResult, PipelineStageInfo } from '@intentos/shared-types'

export interface GenProgress {
  stage: 'codegen' | 'compile' | 'bundle' | 'complete' | 'error'
  progress: number
  message: string
}

export interface GenError {
  message: string
  code: string
}

// Phase: 1 = Skill selection, 2 = planning, 3 = mock preview, 4 = pipeline progress, 5 = complete
type Phase = 1 | 2 | 3 | 4 | 5

interface GenerationStore {
  phase: Phase
  sessionId: string | null

  // Phase 2: planning
  planChunks: PlanChunk[]
  planResult: PlanResult | null
  isPlanning: boolean

  // Phase 3: mock preview
  mockHtml: string
  isMockPartial: boolean

  // Phase 4: pipeline progress (replaces old phase 3)
  pipelineStages: PipelineStageInfo[]
  pipelineOverallProgress: number
  pipelineCurrentStage: string | null

  // Legacy gen progress (for backward compat)
  genProgress: GenProgress | null
  isGenerating: boolean
  genError: GenError | null
  genComplete: boolean

  // actions
  setPhase: (phase: Phase) => void
  setSessionId: (id: string) => void
  appendPlanChunk: (chunk: PlanChunk) => void
  setPlanResult: (result: PlanResult) => void
  setIsPlanning: (v: boolean) => void
  setMockHtml: (html: string, isPartial: boolean) => void
  setPipelineStatus: (stages: PipelineStageInfo[], overallProgress: number, currentStage: string | null) => void
  setGenProgress: (p: GenProgress) => void
  setIsGenerating: (v: boolean) => void
  setGenError: (e: GenError | null) => void
  setGenComplete: (v: boolean) => void

  startPlan: (skillIds: string[], intent: string) => Promise<void>
  refinePlan: (feedback: string) => Promise<void>
  requestMock: () => Promise<void>
  reviseMock: (feedback: string) => Promise<void>
  approveMock: () => Promise<void>
  confirmGenerate: (appName: string) => Promise<void>
  reset: () => void
}

const initialState = {
  phase: 1 as Phase,
  sessionId: null as string | null,
  planChunks: [] as PlanChunk[],
  planResult: null as PlanResult | null,
  isPlanning: false,
  mockHtml: '',
  isMockPartial: false,
  pipelineStages: [] as PipelineStageInfo[],
  pipelineOverallProgress: 0,
  pipelineCurrentStage: null as string | null,
  genProgress: null as GenProgress | null,
  isGenerating: false,
  genError: null as GenError | null,
  genComplete: false,
}

export const useGenerationStore = create<GenerationStore>((set, get) => ({
  ...initialState,

  setPhase: (phase) => set({ phase }),
  setSessionId: (id) => set({ sessionId: id }),
  appendPlanChunk: (chunk) =>
    set((s) => ({ planChunks: [...s.planChunks, chunk] })),
  setPlanResult: (result) => set({ planResult: result }),
  setIsPlanning: (v) => set({ isPlanning: v }),
  setMockHtml: (html, isPartial) => set({ mockHtml: html, isMockPartial: isPartial }),
  setPipelineStatus: (stages, overallProgress, currentStage) =>
    set({ pipelineStages: stages, pipelineOverallProgress: overallProgress, pipelineCurrentStage: currentStage }),
  setGenProgress: (p) => set({ genProgress: p }),
  setIsGenerating: (v) => set({ isGenerating: v }),
  setGenError: (e) => set({ genError: e }),
  setGenComplete: (v) => set({ genComplete: v }),

  startPlan: async (skillIds, intent) => {
    set({ sessionId: null, planChunks: [], planResult: null, isPlanning: true, genError: null })
    try {
      // sessionId is generated by the main process and returned synchronously.
      // We must NOT generate our own UUID — the IPC push channels use the main-process ID.
      const result = await window.intentOS.generation.startPlan({ skillIds, intent })
      const sessionId: string = (result as any)?.data?.sessionId ?? (result as any)?.sessionId
      // Store sessionId so GenerationWindow useEffect re-runs and subscribes to chunk events.
      // Streaming starts asynchronously on the main side after this invoke returns,
      // so the subscription is guaranteed to be in place before the first chunk arrives.
      set({ sessionId, phase: 2 })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isPlanning: false,
        genError: { message, code: 'START_PLAN_FAILED' },
      })
      throw err
    }
  },

  refinePlan: async (feedback) => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ isPlanning: true, planChunks: [] })
    try {
      await window.intentOS.generation.refinePlan({ sessionId, feedback })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isPlanning: false,
        genError: { message, code: 'REFINE_PLAN_FAILED' },
      })
      throw err
    }
  },

  requestMock: async () => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ mockHtml: '', isMockPartial: true, phase: 3, genError: null })
    try {
      await window.intentOS.generation.requestMock({ sessionId })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({ genError: { message, code: 'MOCK_REQUEST_FAILED' } })
      throw err
    }
  },

  reviseMock: async (feedback) => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ mockHtml: '', isMockPartial: true, genError: null })
    try {
      await window.intentOS.generation.reviseMock({ sessionId, feedback })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({ genError: { message, code: 'MOCK_REVISE_FAILED' } })
      throw err
    }
  },

  approveMock: async () => {
    const { sessionId } = get()
    if (!sessionId) return
    try {
      await window.intentOS.generation.approveMock({ sessionId })
      // After approving mock, transition to phase 4 (pipeline progress)
      // The actual pipeline will be started by confirmGenerate
      set({ phase: 4 })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({ genError: { message, code: 'MOCK_APPROVE_FAILED' } })
      throw err
    }
  },

  confirmGenerate: async (appName) => {
    const { sessionId } = get()
    if (!sessionId) return
    set({ isGenerating: true, genError: null, phase: 4 })
    try {
      // Call the pipeline-based generation (generation:start-pipeline)
      // instead of the legacy generation:confirm-generate handler.
      // The pipeline emits generation:pipeline-status events that drive PipelineProgressView.
      await window.intentOS.generation.startPipeline({ sessionId, appName })
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      set({
        isGenerating: false,
        genError: { message, code: 'CONFIRM_GENERATE_FAILED' },
      })
      throw err
    }
  },

  reset: () => set({ ...initialState }),
}))
